# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/frontend/forum/models/channel/columns.yaml

# Model Class name
modelClass: Frontend\Forum\Models\Channel

# List Title
title: Manage Channels

# Link URL for each record
recordUrl: frontend/forum/channels/update/:id

# Message to display if the list is empty
noRecordsMessage: No records

# Records to display per page
recordsPerPage: 20

# Display checkboxes next to each record
showCheckboxes: true

showTree: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: Search...
