# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Channels

# Model Form Field configuration
form: ~/plugins/frontend/forum/models/channel/fields.yaml

# Model Class name
modelClass: Frontend\Forum\Models\Channel

# Default redirect location
defaultRedirect: frontend/forum/channels

# Create page
create:
    title: Create Channels
    redirect: frontend/forum/channels/update/:id
    redirectClose: frontend/forum/channels

# Update page
update:
    title: Edit Channels
    redirect: frontend/forum/channels
    redirectClose: frontend/forum/channels

# Preview page
preview:
    title: Preview Channels
